version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: factus-mysql
    environment:
      MYSQL_DATABASE: factus
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - factus-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: factus-app
    depends_on:
      - mysql
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - factus-network
    restart: always

volumes:
  mysql_data:

networks:
  factus-network:
